--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend.lua"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")
Scene:setLocalZOrder(0)

--Create Panel_Right
local Panel_Right = ccui.Layout:create()
Panel_Right:ignoreContentAdaptWithSize(false)

Panel_Right:setClippingEnabled(false)
Panel_Right:setBackGroundImageCapInsets(cc.rect(0,0,0,0))
Panel_Right:setBackGroundColor(cc.c3b(150, 200, 255))
Panel_Right:setBackGroundColor(cc.c3b(150, 200, 255),cc.c3b(255, 255, 255))
Panel_Right:setBackGroundColorVector(cc.p(0,1))
Panel_Right:setBackGroundColorType(1)
Panel_Right:setBackGroundColorOpacity(102)
Panel_Right:setBackGroundImageScale9Enabled(false)

Panel_Right:setTouchEnabled(true)
Panel_Right:setLayoutComponentEnabled(true)
Panel_Right:setName("Panel_Right")
Panel_Right:setLocalZOrder(0)
Panel_Right:setTag(5)
Panel_Right:setCascadeColorEnabled(true)
Panel_Right:setCascadeOpacityEnabled(true)
Panel_Right:setVisible(true)
Panel_Right:setAnchorPoint(0, 0)
Panel_Right:setPosition(660, 0)
Panel_Right:setScaleX(1)
Panel_Right:setScaleY(1)
Panel_Right:setRotation(0)
Panel_Right:setRotationSkewX(0)
Panel_Right:setRotationSkewY(0)
Panel_Right:setOpacity(255)
Panel_Right:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_Right)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.6875)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.3125)
layout:setPercentHeight(1)

layout:setSize(cc.size(300, 640))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(660)
layout:setRightMargin(0)
layout:setTopMargin(0)
layout:setBottomMargin(0)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Scene:addChild(Panel_Right)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

